[model]
model = "gpt-4o"

[environment]
type = "dev"

[timeout]
llm = 30

[sample_prompts]
prompts = [
  "Can I get alpha index?",
  "Give beta index with explanations",
  "How performed monthly narrative index?"
]